Repository Palashio/libra, pull requests merged in 2020-06, with the labels that each got.

#132 Fixed and generalized text classification query
  queries/nlp_queries.py
  queries/prediction_queries.py
Labels: language

#147 Implement rough MCA idea for reducing dimensionality of one hot columns
  .gitignore
  preprocessing/data_preprocesser.py
  queries/classification_models.py
  queries/dimensionality_red_queries.py
  queries/feedforward_nn.py
  queries/prediction_queries.py
Labels: data

#167 Switch from MCA to CA and set CA to use optimal n_components
  libra/preprocessing/data_preprocesser.py
  libra/queries/dimensionality_red_queries.py
  libra/queries/prediction_queries.py
Labels: data

#194 Added modularity to CNN
  libra/preprocessing/data_reader.py
  libra/preprocessing/image_preprocesser.py
  libra/queries.py
  libra/query/feedforward_nn.py
  libra/query/unused_functions.py
Labels: data

#197 Fix nlp results
  libra/modeling/prediction_model_creation.py
  libra/plotting/nonkeras_generate_plots.py
  libra/preprocessing/NLP_preprocessing.py
  libra/preprocessing/huggingface_model_finetune_helper.py
  libra/queries.py
  libra/query/nlp_queries.py
  libra/query/supplementaries.py
  requirements.txt
  tools/data/nlp_data/image-caption.csv
Labels: language

#198 Set neural net query to use at most 50 classes for classification
  libra/preprocessing/data_preprocesser.py
  libra/queries.py
  libra/query/feedforward_nn.py
Labels: core-ai

#200 Organized utility functions and included plotting
  libra/queries.py
  libra/query/supplementaries.py
  model0.json
  weights0.h5
Labels: enhancement
